# Generated by Django 4.1.5 on 2023-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_company_options_job_hotness_job_num_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
