# Generated by Django 4.1.5 on 2023-01-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_company_description_alter_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
