# Generated by Django 4.1.5 on 2023-01-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="approved",
            field=models.CharField(
                choices=[("A", "Approved"), ("P", "Pending"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
