# Generated by Django 4.1.5 on 2023-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_rename_salarymax_job_salary_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
