# Generated by Django 4.1.5 on 2023-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_alter_location_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
