# Generated by Django 4.1.5 on 2023-01-11 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_job_salary_max_alter_job_salary_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
