# Generated by Django 4.1.5 on 2023-01-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
