# Generated by Django 4.1.5 on 2023-01-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_jobs",
            field=models.ManyToManyField(to="jobs.job"),
        ),
    ]
